/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class EmailDeliverySchema extends BaseModel {
  static $columns = ['attachments', 'attempts', 'createdAt', 'data', 'error', 'id', 'nextRetryAt', 'sentAt', 'status', 'template', 'toEmail', 'updatedAt'] as const
  $columns = EmailDeliverySchema.$columns
  @column()
  declare attachments: string | null
  @column()
  declare attempts: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: string
  @column()
  declare error: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare nextRetryAt: DateTime | null
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare template: string
  @column()
  declare toEmail: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
