/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class OrganizationSchema extends BaseModel {
  static $columns = ['createdAt', 'domain', 'id', 'name', 'status', 'suspendedAt', 'suspendedMessage', 'updatedAt'] as const
  $columns = OrganizationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare domain: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare status: string
  @column.dateTime()
  declare suspendedAt: DateTime | null
  @column()
  declare suspendedMessage: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ServiceClosureSchema extends BaseModel {
  static $columns = ['createdAt', 'endDate', 'id', 'label', 'serviceId', 'startDate', 'updatedAt'] as const
  $columns = ServiceClosureSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare endDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare serviceId: number
  @column.date()
  declare startDate: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ServiceSchema extends BaseModel {
  static $columns = ['closedMessage', 'coverImageData', 'coverImageMimeType', 'coverImageUpdatedAt', 'createdAt', 'id', 'logoData', 'logoMimeType', 'logoUpdatedAt', 'name', 'numcli', 'openingDays', 'openingEndTime', 'openingStartTime', 'orgId', 'saisieMode', 'serviceType', 'slug', 'status', 'updatedAt'] as const
  $columns = ServiceSchema.$columns
  @column()
  declare closedMessage: string | null
  @column()
  declare coverImageData: Buffer | null
  @column()
  declare coverImageMimeType: string | null
  @column.dateTime()
  declare coverImageUpdatedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare logoData: Buffer | null
  @column()
  declare logoMimeType: string | null
  @column.dateTime()
  declare logoUpdatedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare numcli: string | null
  @column()
  declare openingDays: any | null
  @column()
  declare openingEndTime: string | null
  @column()
  declare openingStartTime: string | null
  @column()
  declare orgId: number
  @column()
  declare saisieMode: string
  @column()
  declare serviceType: string
  @column()
  declare slug: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TenantDatabaseSchema extends BaseModel {
  static $columns = ['appName', 'createdAt', 'dbHost', 'dbName', 'dbPasswordEnc', 'dbPort', 'dbUser', 'id', 'lastMigrationBatch', 'orgId', 'serviceId', 'serviceType', 'status', 'updatedAt'] as const
  $columns = TenantDatabaseSchema.$columns
  @column()
  declare appName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dbHost: string
  @column()
  declare dbName: string
  @column()
  declare dbPasswordEnc: string
  @column()
  declare dbPort: number
  @column()
  declare dbUser: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastMigrationBatch: number | null
  @column()
  declare orgId: number
  @column()
  declare serviceId: number
  @column()
  declare serviceType: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserPasswordHistorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'passwordHash', 'userId'] as const
  $columns = UserPasswordHistorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare passwordHash: string
  @column()
  declare userId: number
}

export class UserServiceAssignmentSchema extends BaseModel {
  static $columns = ['assignedAt', 'canManageTariffs', 'canScan', 'canSell', 'canToggleService', 'canViewHistory', 'id', 'serviceId', 'userId'] as const
  $columns = UserServiceAssignmentSchema.$columns
  @column.dateTime()
  declare assignedAt: DateTime
  @column()
  declare canManageTariffs: boolean
  @column()
  declare canScan: boolean
  @column()
  declare canSell: boolean
  @column()
  declare canToggleService: boolean
  @column()
  declare canViewHistory: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare serviceId: number
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'firstName', 'id', 'lastLoginAt', 'lastName', 'mustChangePassword', 'orgId', 'passwordChangedAt', 'passwordHash', 'role', 'status', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare lastName: string | null
  @column()
  declare mustChangePassword: boolean
  @column()
  declare orgId: number
  @column.dateTime()
  declare passwordChangedAt: DateTime | null
  @column()
  declare passwordHash: string
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
