#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER "$SVC_BILLETTERIE_USER" WITH PASSWORD '$SVC_BILLETTERIE_PASSWORD';
  CREATE DATABASE "$SVC_BILLETTERIE_DB" OWNER "$SVC_BILLETTERIE_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$SVC_BILLETTERIE_DB" <<-EOSQL
  GRANT ALL ON SCHEMA public TO "$SVC_BILLETTERIE_USER";
  ALTER SCHEMA public OWNER TO "$SVC_BILLETTERIE_USER";
EOSQL
