#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER "$SVC_FACTURES_USER" WITH PASSWORD '$SVC_FACTURES_PASSWORD';
  CREATE DATABASE "$SVC_FACTURES_DB" OWNER "$SVC_FACTURES_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$SVC_FACTURES_DB" <<-EOSQL
  GRANT ALL ON SCHEMA public TO "$SVC_FACTURES_USER";
  ALTER SCHEMA public OWNER TO "$SVC_FACTURES_USER";
EOSQL
