#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER "$SVC_GESTION_USER" WITH PASSWORD '$SVC_GESTION_PASSWORD';
  CREATE DATABASE "$SVC_GESTION_DB" OWNER "$SVC_GESTION_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$SVC_GESTION_DB" <<-EOSQL
  GRANT ALL ON SCHEMA public TO "$SVC_GESTION_USER";
  ALTER SCHEMA public OWNER TO "$SVC_GESTION_USER";
EOSQL
