#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER "$SVC_MAIL_USER" WITH PASSWORD '$SVC_MAIL_PASSWORD';
  CREATE DATABASE "$SVC_MAIL_DB" OWNER "$SVC_MAIL_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$SVC_MAIL_DB" <<-EOSQL
  GRANT ALL ON SCHEMA public TO "$SVC_MAIL_USER";
  ALTER SCHEMA public OWNER TO "$SVC_MAIL_USER";
EOSQL
