/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class FailedInvoiceMailSchema extends BaseModel {
  static $columns = ['attempts', 'createdAt', 'id', 'invoiceId', 'nextRetryAt', 'updatedAt'] as const
  $columns = FailedInvoiceMailSchema.$columns
  @column()
  declare attempts: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invoiceId: number
  @column.dateTime()
  declare nextRetryAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class InvoiceSchema extends BaseModel {
  static $columns = ['amountCents', 'clientNumber', 'collectedAt', 'createdAt', 'depositedAt', 'fiscalYear', 'hospitalReference', 'id', 'objectLabel', 'orgId', 'payerEmail', 'payfipIdOp', 'paymentReference', 'paymentRequestId', 'serviceId', 'status', 'updatedAt'] as const
  $columns = InvoiceSchema.$columns
  @column()
  declare amountCents: number
  @column()
  declare clientNumber: string | null
  @column.dateTime()
  declare collectedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare depositedAt: DateTime | null
  @column()
  declare fiscalYear: number
  @column()
  declare hospitalReference: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare objectLabel: string
  @column()
  declare orgId: number
  @column()
  declare payerEmail: string | null
  @column()
  declare payfipIdOp: string | null
  @column()
  declare paymentReference: string | null
  @column()
  declare paymentRequestId: number | null
  @column()
  declare serviceId: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
