/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BudgetCodeSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'label', 'numcli', 'orgId', 'updatedAt'] as const
  $columns = BudgetCodeSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare numcli: string
  @column()
  declare orgId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FailedTicketMailSchema extends BaseModel {
  static $columns = ['attempts', 'createdAt', 'id', 'nextRetryAt', 'orderId', 'updatedAt'] as const
  $columns = FailedTicketMailSchema.$columns
  @column()
  declare attempts: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare nextRetryAt: DateTime
  @column()
  declare orderId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderLineSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'orderId', 'quantity', 'tariffType', 'unitPriceCents'] as const
  $columns = OrderLineSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number
  @column()
  declare quantity: number
  @column()
  declare tariffType: string
  @column()
  declare unitPriceCents: number
}

export class OrderSchema extends BaseModel {
  static $columns = ['agentId', 'createdAt', 'email', 'id', 'orgId', 'otpVerifiedAt', 'payfipIdOp', 'paymentMethod', 'paymentReference', 'paymentRequestId', 'qtyTickets', 'retryCount', 'serviceId', 'status', 'totalAmountCents', 'updatedAt', 'visitDate'] as const
  $columns = OrderSchema.$columns
  @column()
  declare agentId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column.dateTime()
  declare otpVerifiedAt: DateTime | null
  @column()
  declare payfipIdOp: string | null
  @column()
  declare paymentMethod: string
  @column()
  declare paymentReference: string | null
  @column()
  declare paymentRequestId: number | null
  @column()
  declare qtyTickets: number
  @column()
  declare retryCount: number
  @column()
  declare serviceId: number
  @column()
  declare status: string
  @column()
  declare totalAmountCents: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.date()
  declare visitDate: DateTime
}

export class OtpCodeSchema extends BaseModel {
  static $columns = ['attempts', 'code', 'createdAt', 'email', 'expiresAt', 'id', 'verifiedAt'] as const
  $columns = OtpCodeSchema.$columns
  @column()
  declare attempts: number
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare verifiedAt: DateTime | null
}

export class ScanSchema extends BaseModel {
  static $columns = ['agentId', 'createdAt', 'id', 'orgId', 'reason', 'result', 'ticketId'] as const
  $columns = ScanSchema.$columns
  @column()
  declare agentId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare reason: string | null
  @column()
  declare result: string
  @column()
  declare ticketId: number | null
}

export class TariffSchema extends BaseModel {
  static $columns = ['budgetCode', 'createdAt', 'id', 'orgId', 'priceCents', 'serviceId', 'status', 'tariffType', 'updatedAt'] as const
  $columns = TariffSchema.$columns
  @column()
  declare budgetCode: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgId: number
  @column()
  declare priceCents: number
  @column()
  declare serviceId: number
  @column()
  declare status: string
  @column()
  declare tariffType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TicketSchema extends BaseModel {
  static $columns = ['consumedAt', 'consumedBy', 'createdAt', 'id', 'orderId', 'orgId', 'priceAtPurchaseCents', 'serviceId', 'status', 'tariffType', 'updatedAt', 'visitDate'] as const
  $columns = TicketSchema.$columns
  @column.dateTime()
  declare consumedAt: DateTime | null
  @column()
  declare consumedBy: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number
  @column()
  declare orgId: number
  @column()
  declare priceAtPurchaseCents: number
  @column()
  declare serviceId: number
  @column()
  declare status: string
  @column()
  declare tariffType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.date()
  declare visitDate: DateTime
}
